### ISSUE TITLE
Chirpstack Support

### ISSUE THREAD

**Issue by chopmann** [ttnmapper/ingress-api#5]
I'd would like to help support chirpstack.
I have experience with the source-code of brocaar's projects and "know enough golang to be dangerous"™

What I found:
https://github.com/ttnmapper/documentation/blob/master/DEVELOPMENT.md

I remember seeing a docker-compose file somewhere, but cant find it anymore.

**Comment by jpmeijers** [comment]
Hi @chopmann. That would be great.

### What we already have

I've added ChirpStack support to the Android App:
https://github.com/ttnmapper/ttnmapper-android-v3/blob/master/app/src/main/java/org/ttnmapper/phonesurveyor/aggregates/AppAggregate.kt#L301

The most important thing to see in the Android code is how the ChirpStack Uplink Event is copied into a TTN Mapper Uplink Message:
https://github.com/ttnmapper/ttnmapper-android-v3/blob/master/app/src/main/java/org/ttnmapper/phonesurveyor/utils/ObjectCopy.kt#L228

There are some fields which TTN Mapper wants, which is not available in the ChirpStack Uplink. I've left them out for now, but hopefully you can help getting them in.

The Android app sends the TTN Mapper Uplink Message json to an endpoint on this ingress-api:
https://github.com/ttnmapper/ingress-api/blob/master/android.go#L117


### What you can contribute

Of course we want support for GPS trackers and other devices to send data via ChirpStack directly to TTN Mapper using an integration. Looking at how I handled the Android case, and also looking at how this is done for TTNv2 and TTSv3 (https://github.com/ttnmapper/ingress-api/blob/master/tts.go), I believe you should be able to add support for ChirpStack.

What I think is needed:
* Add a route /chirp/v3 (major version to identify the json format we will receive)
* Add the function to parse and copy fields into the TtnMapperUplinkMessage (like func PostTtnV2)
* Identify the specific LoRaWAN network instance. I normally fall back to the IP address of where the data comes from (`packetOut.NetworkAddress = r.RemoteAddr`), but if ChirpStack has any other unique identifier per installation, we can use that too. I think in the Android App I use the configured MQTT hostname. But we need to make sure these two match, so we might need to change Android to use the IP too.


### How to test

This repo contains a Dockerfile which can be used to build and run this microservice. But I normally just run the project inside Goland during development. The docker-compose.yaml is kept private as it contains sensitive information like the internal server hostnames, ports and credentials. I don't believe it's necessary to spin up the entire stack to add ChirpStack support. As long as a valid TtnMapperUplinkMessage json object is published on a RabbitMQ queue, all should work correctly from there. The rest of the stack after the Ingress API is network server agnostic, and relies on the NetworkType with the NetworkAddress field to identify different unique LoRaWAN network instances.


### Anything else

We can have a call sometime to discuss. Pop me an email at info@ttnmapper.org and we can schedule it.

**Comment by chopmann** [comment]
Thank you for your response. I'll start working on a PR asap

**Comment by chopmann** [comment]
Have to add some tests, but I think i got the gist of it:
https://github.com/wobcom/ingress-api/commit/f03e3a8a026c2140ac17c00d90fe401f7ffbe0d9

**Comment by jpmeijers** [comment]
Looks very good. I'll give it a proper review when you file a PR.
